<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrustMarket.NotificationService.Application\TrustMarket.NotificationService.Application.csproj" />
    <ProjectReference Include="..\TrustMarket.NotificationService.Infrastructure\TrustMarket.NotificationService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
